In [26]:
import numpy as np

In [55]:
# Creating random arrays

np.random.seed(75)
print(np.random.rand(2,3))
print(np.random.randint(1,10,10))
print(np.random.randint(1,10,size=(2,5)))
print(np.random.normal(10,1,size=10))

[[ 0.56894022  0.06596423  0.88811067]
 [ 0.92965818  0.67969204  0.54427582]]
[8 8 7 4 7 5 5 1 1 1]
[[5 1 2 4 7]
 [4 7 1 2 9]]
[ 11.07845754  10.59611431   9.68603144  10.09306814   9.53687831
   9.76017598  10.43208362  10.28188703  10.23508651   9.87204416]


In [56]:
# Shaping arrays

a1 = np.random.randint(1,10,size=(4,5))
a1

array([[7, 2, 4, 5, 5],
       [9, 5, 6, 3, 6],
       [5, 5, 6, 1, 1],
       [1, 6, 2, 3, 2]])

In [57]:
# Array functions sum,prod,max,min,mean,std
print(a1.sum())
print(a1.sum(axis=0))  # sum of columns (sum of rows axis = 0)
print(a1.sum(axis=1))  # sum of rows (sum of columns axis = 1)

84
[22 18 18 12 14]
[23 29 18 14]


In [64]:
print(a1)
print(np.shape(a1))
print(np.shape(a1)[0])
print(np.shape(a1)[1])
print(np.size(a1))

[[7 2 4 5 5]
 [9 5 6 3 6]
 [5 5 6 1 1]
 [1 6 2 3 2]]
(4, 5)
4
5
20


In [23]:
def get_max_index(a):
    for i in range(len(a)):
        if (a[i] == a.max()):
            return i

def test_run():
    a = np.array([9, 6, 2, 3, 12, 14, 7, 10], dtype=np.int32)  # 32-bit integer array
    print "Array:", a
    
    # Find the maximum and its index in array
    print "Maximum value:", a.max()
    print "Index of max.:", get_max_index(a)


if __name__ == "__main__":
    test_run()


Array: [ 9  6  2  3 12 14  7 10]
Maximum value: 14
Index of max.: 5


In [25]:
# We can use argmax() instead previous loop

import numpy as np

def get_max_index(a):
    return np.argmax(a)

def test_run():
    a = np.array([9, 6, 2, 3, 12, 14, 7, 10], dtype=np.int32)  # 32-bit integer array
    print "Array:", a
    
    # Find the maximum and its index in array
    print "Maximum value:", a.max()
    print "Index of max.:", get_max_index(a)


if __name__ == "__main__":
    test_run()


 Array: [ 9  6  2  3 12 14  7 10]
Maximum value: 14
Index of max.: 5
